### ISSUE TITLE
Checkboxes issues

### ISSUE THREAD

**Issue by hgani** [accessd/rails-settings-ui#23]
Hi,

I'd like to report a couple of problems.

1. Not sure if this is a bug or it's by design.

If I use symbols as checkbox options such as the following:
defaults[:platforms] = [:android, :blackberry, :web]

The checkboxes do not get checked accordingly. They always look unchecked even though the value is in the array.

The workaround is to use strings instead, such as the following
defaults[:platforms] = ['android', 'blackberry', 'web']

2. I can't leave all the boxes unchecked. There has to be at least one box that is checked. When I uncheck all boxes and submit, nothing changes. The last set of boxes that were checked remain checked.

Thanks

**Comment by fesstor** [comment]
Fix for second issue: https://github.com/accessd/rails-settings-ui/pull/24.
