### ISSUE TITLE
Custom class name: Setting

### ISSUE THREAD

**Issue by BGordts** [accessd/rails-settings-ui#26]
If I do in the initializer:

RailsSettingsUi.setup do |config|
    #config.ignored_settings = [:company_name] # Settings not displayed in the interface
    config.settings_class = "Setting" # Customize settings class name
 end

I get

undefined method `each_pair' for nil:NilClass

when I go to /settings

**Comment by accessd** [comment]
Hi! Please give me full trace of your error. And what version of rails-settings-ui and Rails are you using?

**Comment by BGordts** [comment]
Hi!

I have been able to solve the issue. I'm using rails 4.0.1 and rails-settings-ui 0.3 (for bootstrap 3). My Class name is Setting.

I had to do the following to solve the issue:

1) in config/initializers/rails_setting_ui.rb add 
```
RailsSettingsUi.settings_class = "Setting" 
```
(like explained in the readm)

2) In my Setting model file I had to add the following method:
```
def self.get_all
    return Setting.all
  end
```

**Comment by accessd** [comment]
Ok! Could you try to update to last gem version and try to remove `get_all` method from Setting model? It should be working, because I fixed it.
