### ISSUE TITLE
loosen up bootstrap dependency

### ISSUE THREAD

**Issue by alexanderadam** [accessd/rails-settings-ui#27]
Hi @accessd,

first of all: thank you very much for your work. :+1:

I really like rails-settings-ui and therefore it just was a logical consequence [to integrate it](https://github.com/screenconcept/qbrick/pull/39) into [qbrick](https://github.com/screenconcept/qbrick).
We refactor the backend [to remove bootstrap](https://github.com/screenconcept/qbrick/tree/features/ui_redesign) but as we currently don't know when this will be finished/stable we are stuck on an old bootstrap version which leads to the situation that resolving of the dependencies lead to  rais-settings-ui version `0.2.1` (because it doesn't rely on a newer bootstrap version).

This version has some bugs that are fixed in newer ones (like submitting "empty" checkboxes leading to an exception).

Would it be possible to loosen the bootstrap dependency or split the gem for projects that render another frontend anyway?

Thank you in advance,
Alex

**Comment by accessd** [comment]
Hi!
Thank you for your positive feedback :smiley: 

I already had problems with version dependency of `bootstrap-saas`. So, I'll remove it.

**Comment by alexanderadam** [comment]
:tada: Awesome! :tada: 
Thank you very much!

**Comment by accessd** [comment]
Pushed new gem version without bootstrap dependency! Please check.

**Comment by alexanderadam** [comment]
Oh I thought that I answered already. 😮
Anyway. It works like charm now.

Thank you!
