### ISSUE TITLE
rails-settings-cached removed defaults support

### ISSUE THREAD

**Issue by raveman** [accessd/rails-settings-ui#33]
https://github.com/huacnlee/rails-settings-cached/commit/70f5cdf10cab8ded1ffbed53b92cee01facd5279

> - Add `config/app.yml` for write you default settings in file (via settingslogic).
> - Removed `SettingsDefaults::DEFAULTS` support.
> - Remove settingslogic, read YML by self implement.

**Comment by raveman** [comment]
Made quick fix: https://github.com/accessd/rails-settings-ui/pull/34

**Comment by neohunter** [comment]
When this will be merged? it seems valid solution for me.

While this is fixed, in case someone wants a workaround for this just add to your setting model:

def defaults
    get_all
  end

**Comment by ozcubepath** [comment]
This fix causes problem when used with globablize gem.

**Comment by Olli** [comment]
def self.defaults
    get_all
end

but it needs to be a class method

**Comment by accessd** [comment]
fixed
