### ISSUE TITLE
Why dont allow to overwrite the views?

### ISSUE THREAD

**Issue by neohunter** [accessd/rails-settings-ui#35]
Right now its rendering the index.html.erb inside the view, why don't make possible to customize this file if it exists on the app views foldeR?

**Comment by neohunter** [comment]
I was trying to do this on the initializer but is not working:

# This is not working, its suppose to overwrite the index method to render a custom view but is not calling the before_filter
```
class RailsSettingsUi::SettingsController < RailsSettingsUi::ApplicationController
  def index
    render "settings/index"
  end
end

```

**Comment by accessd** [comment]
Yep, you can override it by creating `app/views/rails_settings_ui/settings/index.html.erb` in your application
