### ISSUE TITLE
BUG update all

### ISSUE THREAD

**Issue by Elvinra** [accessd/rails-settings-ui#37]
I have a bug when i update all my settings

A KeyError occurred in settings#update_all:

  key not found: :registry

gem 'rails-settings-ui'
gem 'rails-settings-cached'

init:

require 'rails-settings-ui'

#= Application-specific
#
# # You can specify a controller for RailsSettingsUi::ApplicationController to inherit from:
RailsSettingsUi.parent_controller = 'ApplicationAdminController' # default: '::ApplicationController'
#
# # Render RailsSettingsUi inside a custom layout (set to 'application' to use app layout, default is RailsSettingsUi's own layout)
RailsSettingsUi::ApplicationController.layout 'application_admin'

Rails.application.config.to_prepare do
  # If you use a *custom layout*, make route helpers available to RailsSettingsUi:
  # RailsSettingsUi.inline_main_app_routes!
  RailsSettingsUi.inline_main_app_routes!
end

**Comment by apinrdw** [comment]
@accessd 
i got same issue, this error might came from accessd#32.

environment:

> Ruby 2.3.0
> Ruby on Rails 5.0.0

error trace: 

> key not found: :registry
> 
> /dry-validation/lib/dry/validation/schema/dsl.rb:19:in `fetch'
> /dry-validation/lib/dry/validation/schema/dsl.rb:19:in `initialize'
> /dry-validation/lib/dry/validation/schema/value.rb:10:in `initialize'
> /rails-settings-ui/lib/rails-settings-ui/settings_form_validator.rb:41:in `new'
> /rails-settings-ui/lib/rails-settings-ui/settings_form_validator.rb:41:in `build_validation_schema'
> /rails-settings-ui/lib/rails-settings-ui/settings_form_validator.rb:31:in `initialize'
> /rails-settings-ui/app/controllers/rails_settings_ui/settings_controller.rb:28:in `new'
> /rails-settings-ui/app/controllers/rails_settings_ui/settings_controller.rb:28:in `validate_settings'

Thanks...

**Comment by joshudev** [comment]
+1

**Comment by joshudev** [comment]
I downgraded to rails-settings-ui 0.5.0 in order to work around this issue for now.

**Comment by ramanbuttar** [comment]
Having the same issue

**Comment by accessd** [comment]
Hey there! Sorry for delay with this issue.
Fixed in master, please try to use `gem 'rails-settings-ui', github: 'accessd/rails-settings-ui'`, it should be work.
Tested with `ruby 2.3.0`, `Rails 5.0.0.1` and `rails-settings-cached 0.5.4`.

It fixes `dry-validation` and Rails 5 integrations.

**Comment by ramanbuttar** [comment]
The latest change is throwing `undefined method `to_unsafe_h' for {"email_reminder_period"=>"biweekly"}:ActionController::Parameters. I'm using an `array` setting. Tried as checkboxes and select. Failing on both. Using `ruby 2.3.1` and `rails 4.1.16`

**Comment by accessd** [comment]
@ramanbuttar Try now, please

**Comment by ramanbuttar** [comment]
@accessd Copied over your latest commit and it's working well. Can you put out a gem release with this change included?

Thanks

**Comment by accessd** [comment]
New version `1.1.0` with fixes has been published.
