### ISSUE TITLE
undefined method `merge' for nil:NilClass

### ISSUE THREAD

**Issue by Innarticles** [accessd/rails-settings-ui#45]
I have been trying to add this gem to my app. 

I am using rails-settings-cached.
Rails 4.2.5
Ruby 2.2.5

`rails-settings-ui (1.1.0) app/controllers/rails_settings_ui/settings_controller.rb:21:in `collection'
activesupport (4.2.5) lib/active_support/callbacks.rb:432:in `block in make_lambda'
activesupport (4.2.5) lib/active_support/callbacks.rb:164:in `call'
activesupport (4.2.5) lib/active_support/callbacks.rb:164:in `block in halting'
activesupport (4.2.5) lib/active_support/callbacks.rb:504:in `call'
activesupport (4.2.5) lib/active_support/callbacks.rb:504:in `block in call'
activesupport (4.2.5) lib/active_support/callbacks.rb:504:in `each'
activesupport (4.2.5) lib/active_support/callbacks.rb:504:in `call'`

I have followed the instructions for setup. I am yet to add the line 
engine root:
rails_settings_ui_url

I don't know where to add it in my app.

**Comment by accessd** [comment]
What version of `rails-settings-cached` do you use?

**Comment by Innarticles** [comment]
rails-settings-cached (0.6.5)

Thanks.

**Comment by joshuatf** [comment]
Same issue here.

**Comment by pkonovalov** [comment]
Same issue, ruby 2.3.3, rails 5.0.1

**Comment by accessd** [comment]
Sorry for delay. Please try now with version from Github.
