### ISSUE TITLE
Couple of small issues & remarks to make this gem even better

### ISSUE THREAD

**Issue by edwardmp** [accessd/rails-settings-ui#46]
Hi,

I've stumbled upon this gem and it looks great and is just what I was looking for. However, I do stumble into a few issues:

- By default RSUI will look for a model called Setting**s**, not Setting which actually makes more sense for a default since rails-settings-cached uses the singular Setting by default. If you don't observe this you'll face a 'could not find constant Settings' error, which can be confusing. To fix i you currently have to change the RSUI config to use Settings rather than Setting as the used class. If you agree I'll file a pull request to change this.

- There's an option to specify multiple items in a default config (e.g. for use in checkboxes or select boxes) but there is no way to specify which of the items is the actual default. E.g. I've got a timezones setting and it lists London, New York, etc. but I want the actual default to be London, but the others to be configurable options in the UI. Right now if multiple default options are listed in the YML file, `Setting.time_zone` returns an array with all options available. I want it to be deterministic and always serve just 1 option.

- In this example, I want to make a option list of all timezones rails support. This can be done using code. I can then insert this code in `app.yml` to dynamically get all supported time zones. Yet, if I want to display them in RSUI as an select box I am obligated to provide translations for them. This is a nuisance since I can't put `ERB` in i18n files. Without a translation it should be able to just use the config value as both label & value in the dropdown.  It isn't possible to have potentially dynamic option values in case a selectbox is used (e.g. populating the dropdown with a list of ActiveRecord instances).

- The `settings_displayed_as_select_tag` option is undocumented. I'll file a pull request for this.

- I want to use the default application layout. This won't work unless I explicitly put this in the RSUI config:

``` ruby
  # Use default layout:
  RailsSettingsUi::ApplicationController.module_eval do
    layout 'application'
  end
```
Why not make this a default?

- This gem supports Rails 3 and up, but in the example snippet explaining how-to implement custom authorization rules ` before_filter` is used, which has been deprecated since Rails 4. Add comment that `before_action` should be used when using Rails 4 and up.

**Comment by accessd** [comment]
Hi! First of all, thank you for your suggestions!

1. Currently you're able to specify settings class name in config:

```
RailsSettingsUi.setup do |config|
  config.settings_class = "Setting"
end
```

it's described in README.

2. > specify which of the items is the actual default

Yeah, currently there's no option for it. We should implement it through configuration, for example like this:

```
RailsSettingsUi.setup do |config|
  config.default_settings = {timezone: 'London'}
end
```

3. > Without a translation it should be able to just use the config value as both label & value in the dropdown

Good option! We need to fix it at `RailsSettingsUi::SettingsHelper.select_tag_field` and `RailsSettingsUi::SettingsHelper.checkboxes_group_field`

4. > Why not make this a default?

You're right, `application` layout should be default

5. > before_action

I've just forgotten about it:) I'll fix it.

I think today I'll make features about defaults in selects and translations!

**Comment by accessd** [comment]
All done:)
