### ISSUE TITLE
unable to install rails-settings-ui

### ISSUE THREAD

**Issue by GaudamThiyagarajan** [accessd/rails-settings-ui#55]
the command ``rails g rails_settings_ui:install`` 

throws  following output

``
Running via Spring preloader in process 47426
Could not find generator 'rails_settings_ui:install'. Maybe you meant 'paper_trail:install', 'bullet:install' or 'jquery:datatables:install'
Run `rails generate --help` for more options.
``

**Comment by accessd** [comment]
try to stop spring with `bin/spring stop` and try again

**Comment by GaudamThiyagarajan** [comment]
Previously was manually installing the gem but when I added the gem to the gem file and did bundle install which fixed the issue.
